django_learning/constructor/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.constructor, name='test_func'),
]

django_learning/mail/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.mail, name='mail'),
]

django_learning/order/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.order, name='order'),
]

django_learning/pizza_constructor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('constructor.urls')),
    path('order/', include('order.urls')),
    path('order/mail/', include('mail.urls'))
]

django_learning/constructor/models.py
from django.db import models


class Group(models.Model):
    name = models.CharField(max_length=255)


class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    group = models.ForeignKey(Group, on_delete=None)

django_learning/order/models.py
from django.db import models

# Create your models here.

django_learning/constructor/forms.py
from django import forms


class OrderForm(forms.Form):
    total_price = forms.FloatField()

django_learning/constructor/views.py
from django.shortcuts import render
from .models import Ingredient
from .models import Group
from .forms import OrderForm


def constructor(request):
    # order_form = OrderForm()
    data = {
        "groups": Group.objects.all(),
        "ingredients": Ingredient.objects.all()
    }
    # return render(request, "index.html", {"order_form": order_form})
    return render(request, 'constructor/constructor.html', data)

django_learning/order/views.py
from django.shortcuts import render
from django.http import HttpResponse
from constructor.models import Ingredient


def order(request):
    if request.method == "POST":
        ings = Ingredient.objects.all()
        orderlist = dict(request.POST.lists())
        total = 0
        for ing in ings:
            total += int(orderlist[str(ing.id)][0]) * ing.price

        data = {
            'total': total
        }
        return render(request, 'order/order.html', data)
    elif request.method == 'GET':
        return HttpResponse('<h1>No order</h1>')

# request.content_params
# Create your views here.

django_learning/constructor/templates/constructor/constructor.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Pizza Constructor</title>
  <style type="text/css">
   #content {
    width: 800px;

    margin: 0 auto 50px;
   }

   #ingredient {
    <!--float: left;-->
    display: inline;
    margin-right: 10px"
   }

   #footer {

    position: fixed;
    left: 0;
    bottom: 0;
    padding: 10px;
    background: #8DB600;
    color: #fff;
    width: 100%;
   }
  </style>
 </head>
<body>
    <div id="content"  >
        <h2 >Тесто</h2>
        <input type="radio" checked name="type" id="ital1"/><label for="ital1">Тонкое</label>
        <input type="radio" name="type" id="amer"/><label for="amer">Толстое</label>
        <form action="/order/" method="post">
        {% for group in groups %}
            <p>
            <h3>{{ group.name }} </h3>
            <div id="ingredient">
            {% for ing in ingredients %}
                {% if group.name == ing.group.name %}
                    <div>
                        <p><label for='{{ ing.id }}'>{{ ing.name }} {{ ing.price }}$</label></p>
                        <input id='{{ ing.id }}' type="number" min=0 name="{{ ing.id }}" value=0>
                        <!--<p><input type="number" name="price" value="1" step="any" required="" id="id_price"></p>-->
                    </div>
                {% endif %}
            {% endfor %}
            </div>
            </p>
        {% endfor %}
            <input type="submit" value="Оформить заказ">
        </form>

    </div>

   <div id="footer" align="center">
        <span>Pizza Constructor by &copy; TheHuman</span>
   </div>
 </body>
</html>

django_learning/order/templates/order/order.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Order</title>
  <style type="text/css">
   #content {
    width: 800px;

    margin: 0 auto 50px;
   }

   #ingredient {
    float: left;
    margin-right: 10px"
   }

   #footer {

    position: fixed;
    left: 0;
    bottom: 0;
    padding: 10px;
    background: #8DB600;
    color: #fff;
    width: 100%;
   }
  </style>
 </head>
<body>
    <div id="content" >
    <form action="mail/" method="post">

        <p>
            <label for='fullname'>Имя:</label>
            <input id="fullname" name="name" value="" type="text">
        </p>
        <p>
            <label for='email'>E-mail</label>
            <input id="email" name="email" value="" type="email">
        </p>
        <p>
            <label for='phone'>Телефон</label>
            <input id="phone" name="phone" value="" type="text">
        </p>
        <p>
            <label for='total'>Сумма заказа:</label>
            <span id="total">{{ total }}$</span>
            <input type="text" name="total" value='{{ total }}$' hidden>
        </p>
        <input type="submit" value="Заказать">
    </form>
    </div>
</body>
</html>